Repository OneYearFourCut/OneYearFourCut, pull requests merged in 2022-12, with the labels that each got.

#3 D25-10 ✨FEAT : params Hash 적용
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/Gallery/GalleryFourPic.tsx
  client/src/GallerySetting/GallerySetting.tsx
  client/src/Intro/RedirectPage.tsx
  client/src/Intro/components/Demo/index.tsx
  client/src/Intro/hooks/AutoRedirect.ts
  client/src/SinglePicture/SinglePicture.tsx
  client/src/UploadPicture/hook/useUpload.tsx
  client/src/shared/components/Modal/hooks/useClipboardCopy.tsx
  client/src/shared/libs/cryption.ts
Labels: enhancement

#2 [D25-6] 알림 도메인 리팩터링, 카카오 로그인시 리다이렉트 로직 수정, 회원 이름 글자수 제한 제거
  server/oneyearfourcut/src/main/.DS_Store
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/Like/entity/ArtworkLike.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/Like/service/ArtworkLikeService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/entity/Alarm.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/event/AlarmEvent.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/event/AlarmEventListener.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/event/AlarmEventPublisher.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/service/AlarmService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/entity/Artwork.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/Comment.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/Reply.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/CommentService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/service/ReplyService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/SecurityConfig.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/handler/OAuth2MemberSuccessHandler.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/AlarmControllerTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/artwork/service/ArtworkServiceTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/like/service/ArtworkLikeServiceTest.java
Labels: bug, enhancement

#13 D25-25
  client/src/Gallery/components/ButtonBox/index.tsx
  client/src/Gallery/components/ButtonBox/style.tsx
  client/src/Gallery/components/FourCut/style.tsx
  client/src/Gallery/components/GalleryInfo/index.tsx
  client/src/Gallery/components/GalleryInfo/style.tsx
  client/src/GallerySetting/components/Input/index.tsx
  client/src/assets/Icon/chat.tsx
  client/src/shared/components/Buttons/index.tsx
Labels: feat

#14 D25-26 채팅방 마크업
  client/src/App.tsx
  client/src/ChatList/api.tsx
  client/src/ChatList/components/ChatWrapper/index.tsx
  client/src/ChatList/components/ChatWrapper/style.tsx
  client/src/ChatList/hooks/useSSE.ts
  client/src/ChatList/index.tsx
  client/src/ChatList/style.tsx
  client/src/assets/Icon/message.tsx
  client/src/shared/styled/Theme.ts
Labels: feat
