Repository OneYearFourCut/OneYearFourCut, pull requests merged in 2023-01, with the labels that each got.

#19 D25-24 채팅방 기능 구현
  client/package-lock.json
  client/package.json
  client/src/AlarmList/hooks/useGetAlarmListInfinite.tsx
  client/src/AlarmList/hooks/useHandleIntersection.tsx
  client/src/AlarmList/hooks/useIntersection.tsx
  client/src/App.tsx
  client/src/Chatroom/api.ts
  client/src/Chatroom/components/ChatComponent.tsx
  client/src/Chatroom/components/ChatContent.tsx
  client/src/Chatroom/components/ChatRoomBody.tsx
  client/src/Chatroom/components/ChatRoomHeader.tsx
  client/src/Chatroom/components/ChatRoomInput.tsx
  client/src/Chatroom/components/style.ts
  client/src/Chatroom/helper/handleData.tsx
  client/src/Chatroom/helper/sock.ts
  client/src/Chatroom/hooks/useGetChatData.tsx
  client/src/Chatroom/index.tsx
  client/src/Chatroom/types.ts
  client/src/Gallery/GalleryFourPic.tsx
  client/src/shared/components/Header/hook/useReceiveAlarm.tsx
  client/src/shared/hooks/.gitkeep
  client/src/shared/libs/.gitkeep
  client/src/shared/styled/Theme.ts
  client/src/shared/utils/axios.ts
  client/src/store/types.ts
Labels: enhancement

#20 [D25-29] 채팅방 목록 SSE 구현하기
  client/src/App.tsx
  client/src/ChatList/components/ChatWrapper/index.tsx
  client/src/ChatList/components/ChatWrapper/style.tsx
  client/src/ChatList/hooks/useSSE.ts
  client/src/ChatList/index.tsx
  client/src/Gallery/components/GalleryInfo/style.tsx
  client/src/assets/Icon/chat.tsx
Labels: feat

#21 D25-30 ✨FEAT : 알람 SSE 토큰 재발급 로직 추가
  client/src/shared/components/Header/api.ts
  client/src/shared/components/Header/hook/useNewAlarms.tsx
  client/src/shared/utils/axios.ts
Labels: enhancement

#16 [D25-20] 알람 SSE 구현, 회원 조회 API memberId 값 추가
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/Like/entity/ArtworkLike.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/controller/AlarmController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/event/AlarmEventListener.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/service/AlarmService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/Comment.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/comment/entity/Reply.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/controller/JWTController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/dto/MemberResponseDto.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/member/entity/Member.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/refreshToken/entity/RefreshToken.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/sse/controller/SseController.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/sse/repository/SseEmitterRepository.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/domain/sse/service/SseService.java
  server/oneyearfourcut/src/main/java/com/codestates/mainproject/oneyearfourcut/global/config/auth/SecurityConfig.java
  server/oneyearfourcut/src/main/resources/application-real.yml
  server/oneyearfourcut/src/main/resources/application.yml
  server/oneyearfourcut/src/main/resources/static/docs/index.html
  server/oneyearfourcut/src/main/resources/templates/index.html
  server/oneyearfourcut/src/main/resources/templates/sse.html
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/alarm/AlarmServiceTest.java
  server/oneyearfourcut/src/test/java/com/codestates/mainproject/oneyearfourcut/domain/member/controller/MemberControllerRestDocsTest.java
Labels: feat

#23 D25 30 재발급로직
  client/src/Chatroom/components/ChatRoomInput.tsx
  client/src/Chatroom/helper/sock.ts
  client/src/Chatroom/index.tsx
  client/src/Chatroom/types.ts
  client/src/shared/components/Header/hook/useNewAlarms.tsx
Labels: enhancement

#24 D25 31 새로운 메세지 처리 및 재연결 로직
  client/src/ChatList/index.tsx
Labels: feat

#25 D25 32
  client/src/App.tsx
  client/src/ChatList/index.tsx
  client/src/Chatroom/index.tsx
  client/src/Gallery/GalleryFourPic.tsx
Labels: feat

#28 D25 33
  client/src/ChatList/index.tsx
  client/src/Gallery/GalleryFourPic.tsx
  client/src/Gallery/api.ts
  client/src/Gallery/components/BottonButton/index.tsx
  client/src/Gallery/components/ButtonBox/index.tsx
  client/src/Gallery/components/ButtonBox/style.tsx
  client/src/Gallery/components/GalleryInfo/index.tsx
  client/src/Gallery/components/GalleryInfo/style.tsx
  client/src/shared/components/Buttons/index.tsx
  client/src/shared/components/Modal/Profile.tsx
  client/src/shared/components/Modal/components/ModalContainer.ts
Labels: feat

#29 D25-31 caching
  client/src/ChatList/index.tsx
  client/src/Chatroom/hooks/useGetChatData.tsx
  client/src/shared/components/Header/hook/useNewAlarms.tsx
  client/src/shared/utils/axios.ts
Labels: bug
